# Generated by Django 3.2.7 on 2021-10-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211022_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='channels',
            field=models.ManyToManyField(blank=True, to='api.Channel'),
        ),
    ]
